### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by klausgao** [nodeca/bag.js#12]
I am using this package: https://github.com/Daemonite/material .
bagjs has a bug. when loading .js files by bagjs, this page (https://github.com/Daemonite/material/blob/master/templates/ui-button.html) can't work normally. you will see when not loading by bagjs, the title will change when you scroll down.
I test bagjs for 2 days, if loading .css, the image files loaded by css will be changed to the root path.

**Comment by klausgao** [comment]
now I test basketjs, it can make the page work normally.

**Comment by puzrin** [comment]
Could you create a minimal test sample how to reproduce? (the best of all - test repo)

**Comment by klausgao** [comment]
ok, will work for it.

**Comment by klausgao** [comment]
I put the sample here https://www.jianguoyun.com/p/DWC42bEQpOTyBRiPuxQ
the page is in Chinese, don't worry just click the green button to download it.
you need to run a local server to test it, so I put a baby_web_server for you.
in the dir XLDownload\material\templates, you see 2 html file named 'ui-button.html' and 'ui-button2.html'.
the ui-button.html is original and the ui-button2.html is changed to load .js with bagjs.
you will see the bug I wrote.

**Comment by klausgao** [comment]
sadly I try the website asking to login to download. wait.

**Comment by puzrin** [comment]
You can create a new repo on github & put files there. That will be more convenient.

**Comment by klausgao** [comment]
http://pan.baidu.com/s/1boXjPX9 put it here, and tested.

**Comment by klausgao** [comment]
thank you dude.

**Comment by puzrin** [comment]
There something strange in your archive - too many files. Minimal example means, it contain as few files as possible to reproduce problem. Those files are not required to be from your app, you can create a special ones to demonstrate th bug.

Could you do it?

**Comment by klausgao** [comment]
http://pan.baidu.com/s/1bp6vGq7  it is the Minimal one.

**Comment by puzrin** [comment]
Sorry, your archive contain too much of code, not related to this bug anyhow. We can not debug it. See this example https://github.com/Kirill89/bagjs-issue-12, try to do something similar and create a new issue. With CSS we could not reproduce bug about broken paths.
