### ISSUE TITLE
how can I know a file is loaded from cache or not?

### ISSUE THREAD

**Issue by klausgao** [nodeca/bag.js#14]
maybe we can have a callback var to tell.

**Comment by puzrin** [comment]
You can override default handlers for js/css and compare if `obj.stamp` is before or after call time.

- timestamp is added on save https://github.com/nodeca/bag.js/blob/2.0.2/bag.js#L734
- https://github.com/nodeca/bag.js/blob/2.0.2/bag.js#L848-L891 default handlers
