### ISSUE TITLE
requiring js/css dynamically

### ISSUE THREAD

**Issue by afrozl** [nodeca/bag.js#16]
Is it possible to load javascript dynamically via ajax/rpc? I should explain what I mean. I have an app that dynamically pulls ins new 'widgets' with their own scoped css and js code. These css and js snippets are stored in mongodb. I would like to be able to use bag.js to require them as needed and store them in local storage ( along with appending them to the appropriate widget element as script and style elements )

Does that make sense?

**Comment by puzrin** [comment]
`.require()` does not care about content type to cache if correct url provided. If you need to inject css/js from json answer - extend injector methods or do it in callback.
