### ISSUE TITLE
Cannot load relative import in css.

### ISSUE THREAD

**Issue by loggerhead** [nodeca/bag.js#18]
For example, I have a style file like:

```css
/* foo.css */
@import url(bar.css);
```

and I call bag.js as the following:

```js
var bag = new window.Bag();
bag.require(["foo.css"]);
```

It will success load `foo.css`, but not load `bar.css`.

**Comment by puzrin** [comment]
Yes, you need to pass full paths. `bag.js` does not know where you are.

**Comment by loggerhead** [comment]
Cannot `bag.js` remeber the host at the beginning, and then loading the files recursively? For the third-party css which I cannot modified, how can I use `bag.js` to load all files when it has some relative urls?

**Comment by puzrin** [comment]
Such tasks should be done in your assets manager module, not in bag.js. This lib does a simple thing - load js/css files by URLs and nothing else.
