### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by sanjukandgal** [nodeca/bag.js#19]
Not working in IE11, getting Syntax error -

.then(data => {
      console.log('loaded', data);
    })

**Comment by puzrin** [comment]
https://github.com/nodeca/bag.js#bagjs---js--css-loader--kv-storage

you need promise polyfill, see readme

**Comment by sanjukandgal** [comment]
I am not getting it can you please make small example of it which should work in IE browser.
Thanks in advance.
