### ISSUE TITLE
[question] Forcing replace of cached scripts

### ISSUE THREAD

**Issue by devel-pa** [nodeca/bag.js#6]
Hi,

I've started playing with your library and looks very useful.

I have a question about the possibility to be able to set (as ex) a file hash (like gulp-rev) and tell loader to retrieve the script from the server and replace the old one even is not expired. 

Ore any other way to achieve that.

Thanks,
Paul

**Comment by puzrin** [comment]
See `.key` property in resource info. Set your hash there.

**Comment by puzrin** [comment]
https://github.com/nodeca/bag.js#requirefiles--callbackerr-data `.key` & `.unique` will be useful, depending on your logic.

**Comment by devel-pa** [comment]
Indeed.
Looks like I didn't read the manual with attention.
Thanks,
Paul
